---
title: "501-project"
output: pdf_document
date: "2022-12-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(mosaic)
library(dplyr)
library(tidyverse)
```


## Load Data

```{r}
adult <- read.table("adult.data", sep = ",")
colnames(adult) <- c("age", "workclass", "fnlwgt", "education", "education_num", "marital_status", "occupation", "relationship", "race", "sex", "capital_gain", "capital_loss", "hours_per_week", "native_country", "fifty_k")
adult
```
```{r}
summary(adult)
```

Checking if average capital gain is different for Female/Male:


```{r}
# adult %>% 
#   group_by(sex) %>% 
#   summarise(record_count = n())

female <- filter(adult, str_detect(sex, 'Female'))
male <- filter(adult, str_detect(sex, 'Male'))

t.test(capital_gain ~ sex, data=adult) # Unpooled
t.test(capital_gain ~ sex, var.equal=TRUE, data=adult)   # Pooled
```

Looking at the p value which is close to 0, we can reject the null hypothesis.
We have evidence that suggests that the true difference in means between group Female and group Male is not equal to 0.
We have evidence to say that there is a difference in the average capital gain of Male and Female

```{r}
t.test(capital_loss ~ sex, data=adult) # Unpooled
t.test(capital_loss ~ sex, var.equal=TRUE, data=adult)   # Pooled
```

```{r}
# adult %>%
#   group_by(race) %>%
#   summarise(record_count = n())

anov_race <- aov(capital_gain ~ race, data = adult)
summary(anov_race)
anov_race

```
```{r}
adult %>%
  group_by(education) %>%
  summarise(record_count = n())

summary(aov(capital_gain ~ education, data = adult))

```



```{r}
real_estate <- read.csv("Real_Estate.csv")
summary(real_estate)
ls(real_estate)

histogram(~Y.house.price.of.unit.area, data=real_estate, nint=20)     #
xyplot(Y.house.price.of.unit.area ~ X3.distance.to.the.nearest.MRT.station,data=real_estate)  # negative trend
m1 <- lm(Y.house.price.of.unit.area ~ X3.distance.to.the.nearest.MRT.station, data=real_estate)
summary(m1)
```